import { useEffect, useState } from 'react'

export default function AnalysisDrawer({ ticker, open, onClose }: { ticker?: string | null, open: boolean, onClose: ()=>void }){
  const [analysis, setAnalysis] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)

  useEffect(()=>{
    if(open && ticker){
      // Immediately show placeholder analysis so drawer opens without delay
      const demo = `• ${ticker} — Company update: New product launch and improving margins.\n• Supply chain pressures easing; watch margins.\n• Macro: USD strength could impact exports.`
      setAnalysis(demo)
      setLoading(false)
    } else {
      setAnalysis(null)
      setLoading(false)
    }
  },[open,ticker])

  if(!open) return null

  return (
    <aside className="card drawer" aria-hidden={!open} role="dialog" aria-label="AI analysis drawer">
      <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:8}}>
        <div>
          <h3 style={{margin:0}}>{ticker} — AI Report</h3>
          <div style={{fontSize:12,color:'#6b7280'}}>Generated by GROQ AI (placeholder)</div>
        </div>
        <div style={{display:'flex',gap:8}}>
          <button onClick={onClose} style={{background:'transparent',border:'none',fontSize:18,cursor:'pointer'}}>✕</button>
        </div>
      </div>

      <div style={{minHeight:200}}>
        <div style={{transition:'opacity 200ms', opacity: loading ? 0.6 : 1}}>
          <pre style={{whiteSpace:'pre-wrap',fontFamily:'inherit',lineHeight:1.6}}>{analysis}</pre>
        </div>
      </div>

      <div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:12}}>
        <button className="button" onClick={()=>{ if(ticker) navigator.clipboard?.writeText(analysis||''); }}>Copy</button>
        <button className="button" onClick={()=>{ if(ticker) { const blob = new Blob([analysis||''], { type: 'text/plain' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `${ticker}_analysis.txt`; a.click(); }}}>Download</button>
      </div>
    </aside>
  )
}
